name: Issue Comment Created

on:
  issue_comment:
    types:
      - created

jobs:
  like-pizza:
    runs-on: ubuntu-latest
    #if: ${{ github.event.comment.body == '/jira ticket' }}
    steps:
    - run: echo ${{ github.event.comment.body }}
    
    # - name: Login
    #   uses: atlassian/gajira-login@v3
    #   env:
    #     JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
    #     JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
    #     JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
    # - name: Create Jira ticket based on comment
    #   id: create
    #   uses: atlassian/gajira-create@v3
    #   with:
    #     project: PACT
    #     issuetype: Task
    #     summary: ${{ github.event.issue.title }}
    #     description: ${{ github.event.issue.body }}
    #     fields: '{"customfield_10006": ${{ toJSON(secrets.JIRA_EPIC_TICKET) }}, "customfield_17401":{"value":${{ toJSON( secrets.JIRA_LAYER_CAKE )}}}}'
          
    - name: Like Comment
      if: steps.create.outputs.issue != ''
      uses: actions/github-script@v4
      with:
        script: |
          const {owner, repo} = context.issue
          github.reactions.createForIssueComment({
            owner,
            repo,
           comment_id: context.payload.comment.id,
           content: "+1",
           });