name: SmartBear Supported Issue Label Added

on:
  issue_comment:
    types:
      - created

jobs:
  call-workflow:
    uses: Ilia/.github/.github/workflows/smartbear-issue-comment-created.yml@master
    secrets: inherit