on:
  issues:
    types:
      - opened

name: Jira Issue Create

jobs:
  build:
    runs-on: ubuntu-latest
    name: Jira Issue Create
    steps:
    - name: Login
      uses: atlassian/gajira-login@v3
      env:
        JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
        JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
        JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}

    - name: Create
      uses: atlassian/gajira-create@v3
      with:
        project: PACT
        issuetype: Task
        summary: ${{ github.event.issue.title }}
        description: ${{ github.event.issue.body }}
        fields: '{"customfield_10006":"PACT-194", "customfield_17401":{"value":"maintenance"}}'
