name: Progress Jira ticket to In Progress

on:
  create:
    branches:
      - 'feature/**'

jobs:
  build:
    runs-on: ubuntu-latest
    name: Transition to In Progress
    steps:
    - name: login
      uses: atlassian/gajira-login@v3
      env:
        JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
        JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
        JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}

    - name: Find Issue
      id: find
      uses: atlassian/gajira-find-issue-key@v3
      with:
        from: branch

    - run: echo "${{ steps.find.outputs.issue }}"

    - name: Transition issue
      if: steps.find.outputs.issue != ''
      uses: atlassian/gajira-transition@v3
      with:
        issue: ${{ steps.find.outputs.issue }}
        transition: "In Progress"
