name: Pull Request Ready for Review

on:
  pull_request:
    types: [opened, reopened]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Request Review with Slack
      uses: Ilia/request-review-action@v0.0.1
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        PULL_REQUEST_NUMBER: ${{ github.event.pull_request.number }}
        PULL_REQUEST_TITLE: ${{ github.event.pull_request.title }}
        PULL_REQUEST_AUTHOR_NAME: ${{ github.event.pull_request.user.login }}
        PULL_REQUEST_AUTHOR_ICON_URL: ${{ github.event.pull_request.user.avatar_url }}
        PULL_REQUEST_URL: ${{ github.event.pull_request.html_url }}
        REPO: ${{ github.event.repository.name }}